pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven local repo

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'Other'

  - task: Maven@3
    inputs:
      goals: 'org.jacoco:jacoco-maven-plugin:prepare-agent package'
      options: '-Dsonar.branch.name='
      jdkVersionOption: 1.11
      sonarQubeRunAnalysis: true
      mavenOptions: '$(MAVEN_OPTS)'
