pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.cache/.gradle
  SONAR_USER_HOME: $(Pipeline.Workspace)/.cache/.sonar

steps:
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts'
      path: $(Pipeline.Workspace)/.cache

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'Other'

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build jacocoTestReport publish'
      options: '--build-cache -Dsonar.branch.name='
      jdkVersionOption: 1.11
      sonarQubeRunAnalysis: true
    env:
      DEPLOY_USERNAME: $(DEPLOY_USERNAME)
      DEPLOY_TOKEN: $(DEPLOY_TOKEN)

  - script: |
      # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
      ./gradlew --stop
