name: Build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Run SonarQube Scanner
      run: ./gradlew sonar
      if: github.ref == 'refs/heads/main'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Release artifacts
      run: ./gradlew publish jreleaserFullRelease
      if: github.ref == 'refs/heads/main'
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_KEY }}
